# Generated by Django 5.2.16 on 2026-07-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedcontent',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='generatedcontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
